"""Bundle the shared workspace into a Chrome side panel; no secrets or run data."""

import base64
import hashlib
import json
import shutil
import struct
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "chrome-extension"
SOURCE = ROOT / "src" / "mimicry" / "web"


def build():
    assets = TARGET / "assets"
    assets.mkdir(exist_ok=True)
    for name in ("app.js", "app.css"):
        shutil.copyfile(SOURCE / name, assets / name)
    inline = assets / "inline"
    inline.mkdir(exist_ok=True)
    for name in ("core.js", "composer.js"):
        shutil.copyfile(SOURCE / "inline" / name, inline / name)
    style = (SOURCE / "inline" / "composer.css").read_text()
    (inline / "styles.js").write_text("window.MimicryInlineCSS = " + json.dumps(style) + ";\n")
    # Keep content.js self-contained, including when an older worker injects only it.
    # Dependency order is fixed at build time, not spread across injection calls.
    bundle = [
        "// Generated by tools/build_extension.py; edit web/inline sources instead.\n",
        (SOURCE / "inline" / "core.js").read_text(),
        "window.MimicryInlineCSS = " + json.dumps(style) + ";\n",
        (SOURCE / "inline" / "composer.js").read_text(),
        (SOURCE / "inline" / "extension-entry.js").read_text(),
    ]
    (TARGET / "content.js").write_text("\n".join(bundle))
    html = (SOURCE / "index.html").read_text()
    html = html.replace('href="/assets/', 'href="assets/').replace('src="/assets/', 'src="assets/')
    html = html.replace(
        '<script src="assets/app.js"',
        '<script src="extension-bridge.js" defer></script>\n  <script src="assets/app.js"',
    )
    html = html.replace('class="brand" href="/"', 'class="brand" href="sidepanel.html"')
    (TARGET / "sidepanel.html").write_text(html)
    manifest = json.loads((TARGET / "manifest.json").read_text())
    identity = "".join(
        chr(97 + int(c, 16))
        for c in hashlib.sha256(base64.b64decode(manifest["key"])).hexdigest()[:32]
    )
    assert identity in (ROOT / "src/mimicry/extension_identity.py").read_text()
    icons = TARGET / "icons"
    icons.mkdir(exist_ok=True)
    # A small geometric M, drawn as a polygon, keeps the extension identifiable.
    polygon = [
        (0.22, 0.74),
        (0.22, 0.27),
        (0.34, 0.27),
        (0.5, 0.48),
        (0.66, 0.27),
        (0.78, 0.27),
        (0.78, 0.74),
        (0.65, 0.74),
        (0.65, 0.47),
        (0.5, 0.66),
        (0.35, 0.47),
        (0.35, 0.74),
    ]

    def inside(x, y):
        hit = False
        previous = polygon[-1]
        for point in polygon:
            x1, y1 = previous
            x2, y2 = point
            if (y1 > y) != (y2 > y) and x < (x2 - x1) * (y - y1) / (y2 - y1) + x1:
                hit = not hit
            previous = point
        return hit

    def chunk(kind, data):
        return (
            struct.pack("!I", len(data)) + kind + data + struct.pack("!I", zlib.crc32(kind + data))
        )

    for size in (16, 48, 128):
        rows = []
        for y in range(size):
            pixels = bytearray([0])
            for x in range(size):
                pixels.extend(
                    (248, 251, 243, 255)
                    if inside((x + 0.5) / size, (y + 0.5) / size)
                    else (83, 100, 200, 255)
                )
            rows.append(pixels)
        png = b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", struct.pack("!2I5B", size, size, 8, 6, 0, 0, 0))
        png += chunk(b"IDAT", zlib.compress(b"".join(rows))) + chunk(b"IEND", b"")
        (icons / f"{size}.png").write_bytes(png)
    print(f"Built chrome-extension/ ({identity}).")


if __name__ == "__main__":
    build()
